# render.yaml - ОБНОВЛЕННАЯ конфигурация для PlasticBoy

services:
  # Основное веб-приложение (карта, админка, API + Telegram webhook)
  - type: web
    name: plasticboy-web
    env: node
    repo: https://github.com/your-username/plasticboy.git
    buildCommand: npm install
    startCommand: npm run render:web
    plan: free
    region: oregon
    branch: main
    rootDir: .
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - fromGroup: plasticboy-env

  # Telegram бот worker (только настройка и мониторинг)
  - type: worker
    name: plasticboy-bot-worker
    env: node
    repo: https://github.com/your-username/plasticboy.git
    buildCommand: npm install
    startCommand: npm run render:bot
    plan: free
    region: oregon
    branch: main
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: plasticboy-env

# Группы переменных окружения
envVarGroups:
  - name: plasticboy-env
    envVars:
      # MongoDB конфигурация
      - key: MONGODB_URI
        value: mongodb+srv://plasticboy:Urod1488@cluster0.ts0h5a6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      
      # Админ панель
      - key: ADMIN_PASSWORD
        value: Urod1488
      
      # Telegram бот конфигурация
      - key: TELEGRAM_BOT_TOKEN
        value: 7623080305:AAHnOVwzUfL8N8O2zr-_vEDDOa-PVKQrmeY
      - key: TELEGRAM_BOT_USERNAME
        value: PlasticBoyBot

# ВАЖНЫЕ ИЗМЕНЕНИЯ В v2:
# 
# 1. WEBHOOK ИНТЕГРАЦИЯ:
#    - Telegram webhook теперь обрабатывается основным веб-сервисом
#    - Worker только настраивает webhook и мониторит состояние
#    - Вся логика бота в server.js
#
# 2. УПРОЩЕННАЯ АРХИТЕКТУРА:
#    - Один сервис обрабатывает и веб-запросы и Telegram
#    - Worker только для настройки и мониторинга
#    - Меньше проблем с синхронизацией
#
# 3. ПРОВЕРКА ПОСЛЕ ДЕПЛОЯ:
#    - Откройте https://your-app-name.onrender.com/health
#    - Проверьте логи web-сервиса в Render Dashboard
#    - Проверьте логи worker-сервиса для настройки
#    - Отправьте /start боту @PlasticBoyBot
#
# 4. TROUBLESHOOTING:
#    - Если бот не отвечает, проверьте логи web-сервиса
#    - Worker должен показать успешную настройку webhook
#    - Убедитесь что оба сервиса запущены
#    - Health check должен показывать telegramWebhook: "configured"
#
# 5. UPGRADE TO PAID PLAN:
#    Для стабильной работы в продакшене рекомендуется 
#    план Starter ($7/месяц) для избежания sleep mode
