# render.yaml - ИСПРАВЛЕННАЯ конфигурация для PlasticBoy

services:
  # Основное веб-приложение (карта, админка, API)
  - type: web
    name: plasticboy-web
    env: node
    repo: https://github.com/your-username/plasticboy.git
    buildCommand: npm install
    startCommand: npm run render:web
    plan: free
    region: oregon
    branch: main
    rootDir: .
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - fromGroup: plasticboy-env

  # Telegram бот (Worker сервис)
  - type: worker
    name: plasticboy-bot
    env: node
    repo: https://github.com/your-username/plasticboy.git
    buildCommand: npm install
    startCommand: npm run render:bot
    plan: free
    region: oregon
    branch: main
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - fromGroup: plasticboy-env

# Группы переменных окружения
envVarGroups:
  - name: plasticboy-env
    envVars:
      # MongoDB конфигурация
      - key: MONGODB_URI
        value: mongodb+srv://plasticboy:Urod1488@cluster0.ts0h5a6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      
      # Админ панель
      - key: ADMIN_PASSWORD
        value: Urod1488
      
      # Telegram бот конфигурация
      - key: TELEGRAM_BOT_TOKEN
        value: 7623080305:AAHnOVwzUfL8N8O2zr-_vEDDOa-PVKQrmeY
      - key: TELEGRAM_BOT_USERNAME
        value: PlasticBoyBot

# ВАЖНЫЕ ПРИМЕЧАНИЯ:
# 
# 1. WEBHOOK SETUP:
#    После деплоя web-сервиса, bot-сервис автоматически настроит webhook
#    используя RENDER_EXTERNAL_URL веб-сервиса
#
# 2. ПРОВЕРКА ПОСЛЕ ДЕПЛОЯ:
#    - Откройте https://your-app-name.onrender.com/health
#    - Проверьте логи bot-сервиса в Render Dashboard
#    - Отправьте /start боту @PlasticBoyBot
#
# 3. TROUBLESHOOTING:
#    - Если бот не отвечает, перезапустите bot-сервис
#    - Проверьте Environment Variables в настройках
#    - Убедитесь что оба сервиса запущены
#
# 4. UPGRADE TO PAID PLAN:
#    Для стабильной работы в продакшене рекомендуется 
#    план Starter ($7/месяц) для избежания sleep mode
