# render.yaml - Исправленная конфигурация для PlasticBoy v2.0
# Только один Web сервис - всё в одном процессе

services:
  # Основное веб-приложение (карта + админка + API + Telegram webhook)
  - type: web
    name: plasticboy-web
    env: node
    repo: https://github.com/codenameh8m/plasticboy.git  # ЗАМЕНИТЕ на ваш репозиторий
    buildCommand: npm install
    startCommand: npm start
    plan: free
    region: oregon
    branch: main
    rootDir: .
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - fromGroup: plasticboy-env

# Группы переменных окружения
envVarGroups:
  - name: plasticboy-env
    envVars:
      # MongoDB конфигурация
      - key: MONGODB_URI
        value: mongodb+srv://plasticboy:Urod1488@cluster0.ts0h5a6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      
      # Админ панель
      - key: ADMIN_PASSWORD
        value: Urod1488
      
      # Telegram бот конфигурация
      - key: TELEGRAM_BOT_TOKEN
        value: 7623080305:AAHnOVwzUfL8N8O2zr-_vEDDOa-PVKQrmeY
      
      - key: TELEGRAM_BOT_USERNAME
        value: PlasticBoyBot

# =============================================================================
# ИНСТРУКЦИИ ПО ДЕПЛОЮ:
# 
# 1. ОБЯЗАТЕЛЬНО замените repo URL на ваш GitHub репозиторий
# 2. Сохраните этот файл как render.yaml в корне проекта
# 3. Замените server.js на исправленную версию
# 4. Сделайте commit и push в GitHub
# 5. В Render Dashboard создайте новый Web Service из GitHub
# 6. Render автоматически прочитает этот файл
# 
# ПОСЛЕ ДЕПЛОЯ - НАСТРОЙКА TELEGRAM WEBHOOK:
# 
# 1. Получите URL вашего приложения (например: https://plasticboy-web.onrender.com)
# 2. Откройте в браузере для настройки webhook:
#    https://your-app-url.onrender.com/setup-webhook
#    
#    Пример:
#    https://plasticboy-web.onrender.com/setup-webhook
#
# 3. Проверьте настройку webhook:
#    https://your-app-url.onrender.com/webhook-info
#
# 4. Проверьте работу бота:
#    - Отправьте /start @PlasticBoyBot в Telegram
#    - Бот должен ответить с кнопками
#
# ПРОВЕРКА РАБОТЫ:
#
# - Health check: https://your-app-url.onrender.com/health
# - Веб-приложение: https://your-app-url.onrender.com
# - Админ панель: https://your-app-url.onrender.com/admin.html
# - Рейтинг: https://your-app-url.onrender.com/leaderboard.html
# - Настройка webhook: https://your-app-url.onrender.com/setup-webhook
# - Информация о webhook: https://your-app-url.onrender.com/webhook-info
#
# TROUBLESHOOTING:
#
# - Если бот не отвечает: 
#   1. Откройте /setup-webhook для настройки
#   2. Проверьте /webhook-info для статуса
#   3. Проверьте логи в Render Dashboard
#
# - Если MongoDB не подключается: проверьте MONGODB_URI в Environment Variables
#
# - Если приложение не запускается: проверьте логи в Render Dashboard
#
# =============================================================================
